# 70 Numpy Exercises

# 1. Import numpy as np and see the version
Q. Import numpy as `np` and print the version number.

    

In [1]:
import numpy as np
np.__version__

'1.14.5'

# 2. How to create a 1D array?
Q. Create a 1D array of numbers from 0 to 9

    

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 3. How to create a boolean array?
Q. Create a 3×3 numpy array of all True’s

    

In [5]:
np.full((3,3), True, dtype='Bool')

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 4. How to extract items that satisfy a given condition from 1D array?
Q. Extract all odd numbers from arr

    

In [15]:
a=np.arange(10)
a_odd=np.mod(a,2)==1
np.extract(a_odd, a)

array([1, 3, 5, 7, 9])

# 5. How to replace items that satisfy a condition with another value in numpy array?
Q. Replace all odd numbers in arr with -1

    

In [19]:
np.place(a, a_odd, -1)
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 6. How to replace items that satisfy a condition without affecting the original array?
Q. Replace all odd numbers in arr with -1 without changing arr

    

In [25]:
a=np.arange(10)
a_odd=np.mod(a,2)==1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 7. How to reshape an array?
Q. Convert a 1D array to a 2D array with 2 rows

    

In [27]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 8. How to stack two arrays vertically?
Q. Stack arrays a and b vertically

    

In [32]:
a = np.arange(10)
b = np.arange(10,20)
c = np.stack((a, b))
c


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

# 9. How to stack two arrays horizontally?
Q. Stack the arrays a and b horizontally.

    

In [33]:
a = np.arange(10)
b = np.arange(10,20)
c = np.stack((a, b), axis = 1)
c

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

# 10. How to generate custom sequences in numpy without hardcoding?
Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:
`a = np.array([1,2,3])`

Desired Output:

`#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`

    

# 11. How to get the common items between two python numpy arrays?
Q. Get the common items between a and b

    

# 12. How to remove from one array those items that exist in another?
Q. From array a remove all items present in array b

    

# 13. How to get the positions where elements of two arrays match?
Q. Get the positions where elements of a and b match

    

# 14. How to extract all numbers between a given range from a numpy array?
Q. Get all items between 5 and 10 from a.

    

# 15. How to make a python function that handles scalars to work on numpy arrays?
Q. Convert the function maxx that works on two scalars, to work on two arrays.

    

# 16. How to swap two columns in a 2d numpy array?
Q. Swap columns 1 and 2 in the array arr.

    

# 17. How to swap two rows in a 2d numpy array?
Q. Swap rows 1 and 2 in the array arr:

    

# 18. How to reverse the rows of a 2D array?
Q. Reverse the rows of a 2D array arr.

    

# 19. How to reverse the columns of a 2D array?
Q. Reverse the columns of a 2D array arr.

    

# 20. How to create a 2D array containing random floats between 5 and 10?
Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

    

# 21. How to print only 3 decimal places in python numpy array?
Q. Print or show only 3 decimal places of the numpy array rand_arr.

    

# 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)

    

# 23. How to limit the number of items printed in output of numpy array?
Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.

    

# 24. How to print the full numpy array without truncating
Q. Print the full numpy array a without truncating.

    

# 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
Q. Import the iris dataset keeping the text intact.

    

# 26. How to extract a particular column from 1D array of tuples?
Q. Extract the text column species from the 1D iris imported in previous question.

    

# 27. How to convert a 1d array of tuples to a 2d numpy array?
Q. Convert the 1D iris to 2D array iris_2d by omitting the species text field.

    

# 28. How to compute the mean, median, standard deviation of a numpy array?
Q. Find the mean, median, standard deviation of iris's sepallength (1st column)

    

# 29. How to normalize an array so the values range exactly between 0 and 1?
Q. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

    

# 30. How to compute the softmax score?
Q. Compute the softmax score of sepallength.

    

# 31. How to find the percentile scores of a numpy array?
Q. Find the 5th and 95th percentile of iris's sepallength

    

# 32. How to insert values at random positions in an array?
Q. Insert np.nan values at 20 random positions in iris_2d dataset

    

# 33. How to find the position of missing values in numpy array?
Q. Find the number and position of missing values in iris_2d's sepallength (1st column)

    

# 34. How to filter a numpy array based on two or more conditions?
Q. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

    

# 35. How to drop rows that contain a missing value from a numpy array?
Q. Select the rows of iris_2d that does not have any nan value.

    

# 36. How to find the correlation between two columns of a numpy array?
Q. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d

    

# 37. How to find if a given array has any null values?
Q. Find out if iris_2d has any missing values.

    

# 38. How to replace all missing values with 0 in a numpy array?
Q. Replace all ccurrences of nan with 0 in numpy array

    

# 39. How to find the count of unique values in a numpy array?
Q. Find the unique values and the count of unique values in iris's species

    

# 40. How to convert a numeric to a categorical (text) array?
Q. Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:

    

# 41. How to create a new column from existing columns of a numpy array?
Q. Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

    

#  42. How to do probabilistic sampling in numpy?
Q. Randomly sample iris's species such that setose is twice the number of versicolor and virginica

    

# 43. How to get the second largest value of an array when grouped by another array?
Q. What is the value of second longest petallength of species setosa

    

# 44. How to sort a 2D array by a column
Q. Sort the iris dataset based on sepallength column.

    

# 45. How to find the most frequent value in a numpy array?
Q. Find the most frequent value of petal length (3rd column) in iris dataset.

    

# 46. How to find the position of the first occurrence of a value greater than a given value?
Q. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.

    

# 47. How to replace all values greater than a given value to a given cutoff?
Q. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

    

# 48. How to get the positions of top n values from a numpy array?
Q. Get the positions of top 5 maximum values in a given array a.

    

# 49. How to compute the row wise counts of all possible values in an array?
Q. Compute the counts of unique values row-wise.

    

# 50. How to convert an array of arrays into a flat 1d array?
Q. Convert array_of_arrays into a flat linear 1d array.

    

# 51. How to generate one-hot encodings for an array in numpy?
Q. Compute the one-hot encodings (dummy binary variables for each unique value in the array)

    

# 52. How to create row numbers grouped by a categorical variable?
Q. Create row numbers grouped by a categorical variable. Use the following sample from iris species as input.

    

# 53. How to create groud ids based on a given categorical variable?
Q. Create group ids based on a given categorical variable. Use the following sample from iris species as input.

    

# 54. How to rank items in an array using numpy?
Q. Create the ranks for the given numeric array a.

    

# 55. How to rank items in a multidimensional array using numpy?
Q. Create a rank array of the same shape as a given numeric array a.

    

# 56. How to find the maximum value in each row of a numpy array 2d?
Q. Compute the maximum for each row in the given array.

    

# 57. How to compute the min-by-max for each row for a numpy array 2d?
Q. Compute the min-by-max for each row for given 2d numpy array.

    

# 58. How to find the duplicate records in a numpy array?
Q. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.

    

# 59. How to find the grouped mean in numpy?
Q. Find the mean of a numeric column grouped by a categorical column in a 2D numpy array

    

# 60. How to convert a PIL image to numpy array?
Q. Import the image from the following URL and convert it to a numpy array.

    

# 61. How to drop all missing values from a numpy array?
Q. Drop all nan values from a 1D numpy array

    

# 62. How to compute the euclidean distance between two arrays?
Q. Compute the euclidean distance between two arrays a and b.

    

# 63. How to find all the local maxima (or peaks) in a 1d array?
Q. Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

    

# 64. How to subtract a 1d array from a 2d array, where each item of 1d array subtracts from respective row?
Q. Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.

    

# 65. How to find the index of n'th repetition of an item in an array
Q. Find the index of 5th repetition of number 1 in x.

    

# 66. How to convert numpy's datetime64 object to datetime's datetime object?
Q. Convert numpy's datetime64 object to datetime's datetime object

    

# 67. How to compute the moving average of a numpy array?
Q. Compute the moving average of window size 3, for the given 1D array.

    

# 68. How to create a numpy array sequence given only the starting point, length and the step?
Q. Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

    

# 69. How to fill in missing dates in an irregular series of numpy dates?
Q. Given an array of a non-continuous sequence of dates. Make it a continuous sequence of dates, by filling in the missing dates.

    

# 70. How to create strides from a given 1D array?
Q. From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

    